namespace SD.Project.Domain.Entities;

/// <summary>
/// Represents an image associated with a product.
/// </summary>
public class ProductImage
{
    /// <summary>
    /// Maximum allowed file size in bytes (5 MB).
    /// </summary>
    public const long MaxFileSizeBytes = 5 * 1024 * 1024;

    /// <summary>
    /// Allowed image content types.
    /// </summary>
    public static readonly IReadOnlyCollection<string> AllowedContentTypes = new[]
    {
        "image/jpeg",
        "image/png",
        "image/webp"
    };

    /// <summary>
    /// Allowed file extensions.
    /// </summary>
    public static readonly IReadOnlyCollection<string> AllowedExtensions = new[]
    {
        ".jpg",
        ".jpeg",
        ".png",
        ".webp"
    };

    public Guid Id { get; private set; }
    public Guid ProductId { get; private set; }

    /// <summary>
    /// Original file name as uploaded by the user.
    /// </summary>
    public string FileName { get; private set; } = default!;

    /// <summary>
    /// Stored file name (unique, generated by the system).
    /// </summary>
    public string StoredFileName { get; private set; } = default!;

    /// <summary>
    /// Content type of the image (e.g., image/jpeg).
    /// </summary>
    public string ContentType { get; private set; } = default!;

    /// <summary>
    /// File size in bytes.
    /// </summary>
    public long FileSizeBytes { get; private set; }

    /// <summary>
    /// URL path to the full-size image.
    /// </summary>
    public string ImageUrl { get; private set; } = default!;

    /// <summary>
    /// URL path to the thumbnail image.
    /// </summary>
    public string ThumbnailUrl { get; private set; } = default!;

    /// <summary>
    /// Indicates whether this is the main (primary) image for the product.
    /// </summary>
    public bool IsMain { get; private set; }

    /// <summary>
    /// Display order for sorting images.
    /// </summary>
    public int DisplayOrder { get; private set; }

    public DateTime CreatedAt { get; private set; }

    private ProductImage()
    {
        // EF Core constructor
    }

    public ProductImage(
        Guid id,
        Guid productId,
        string fileName,
        string storedFileName,
        string contentType,
        long fileSizeBytes,
        string imageUrl,
        string thumbnailUrl,
        bool isMain = false,
        int displayOrder = 0)
    {
        if (id == Guid.Empty)
        {
            throw new ArgumentException("Image ID cannot be empty", nameof(id));
        }

        if (productId == Guid.Empty)
        {
            throw new ArgumentException("Product ID cannot be empty", nameof(productId));
        }

        if (string.IsNullOrWhiteSpace(fileName))
        {
            throw new ArgumentException("File name is required", nameof(fileName));
        }

        if (string.IsNullOrWhiteSpace(storedFileName))
        {
            throw new ArgumentException("Stored file name is required", nameof(storedFileName));
        }

        if (string.IsNullOrWhiteSpace(contentType))
        {
            throw new ArgumentException("Content type is required", nameof(contentType));
        }

        if (fileSizeBytes <= 0)
        {
            throw new ArgumentException("File size must be greater than zero", nameof(fileSizeBytes));
        }

        if (string.IsNullOrWhiteSpace(imageUrl))
        {
            throw new ArgumentException("Image URL is required", nameof(imageUrl));
        }

        if (string.IsNullOrWhiteSpace(thumbnailUrl))
        {
            throw new ArgumentException("Thumbnail URL is required", nameof(thumbnailUrl));
        }

        Id = id;
        ProductId = productId;
        FileName = fileName;
        StoredFileName = storedFileName;
        ContentType = contentType;
        FileSizeBytes = fileSizeBytes;
        ImageUrl = imageUrl;
        ThumbnailUrl = thumbnailUrl;
        IsMain = isMain;
        DisplayOrder = displayOrder;
        CreatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Sets this image as the main image for the product.
    /// </summary>
    public void SetAsMain()
    {
        IsMain = true;
    }

    /// <summary>
    /// Clears the main image flag.
    /// </summary>
    public void ClearMainFlag()
    {
        IsMain = false;
    }

    /// <summary>
    /// Updates the display order.
    /// </summary>
    public void UpdateDisplayOrder(int order)
    {
        if (order < 0)
        {
            throw new ArgumentException("Display order cannot be negative", nameof(order));
        }

        DisplayOrder = order;
    }

    /// <summary>
    /// Validates if a file is an allowed image type.
    /// </summary>
    public static bool IsAllowedContentType(string contentType)
    {
        return !string.IsNullOrWhiteSpace(contentType) &&
               AllowedContentTypes.Contains(contentType.ToLowerInvariant());
    }

    /// <summary>
    /// Validates if a file extension is allowed.
    /// </summary>
    public static bool IsAllowedExtension(string extension)
    {
        return !string.IsNullOrWhiteSpace(extension) &&
               AllowedExtensions.Contains(extension.ToLowerInvariant());
    }

    /// <summary>
    /// Validates if a file size is within the allowed limit.
    /// </summary>
    public static bool IsAllowedFileSize(long fileSizeBytes)
    {
        return fileSizeBytes > 0 && fileSizeBytes <= MaxFileSizeBytes;
    }
}
